### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by kbrabrand**
Switched to using the Imboclient instead of guzzle directly, and rewrote most of the feature file as a consequence of this. The suite now passes most of the tests, and the failing ones are caused by a few pieces of the ES backend implementation still missing.

Large parts of the context files has been copied from the Behat suite in the Imbo project. Need to figure out how to give proper attribution..

### CODE REVIEW

**Comment by fangel** [comment]
I think it looks great! What's the reason for disabling the Behat tests on Travis?

**Comment by kbrabrand** [comment]
The behat test execution failed with 500 internal errors from the PHP server. Will look into it in order to get them to run.

**Comment by kbrabrand** [comment]
But I won't spend the time right now, so I guess merging without behat is ok for now as long as the rest is ok..

**Comment by fangel** [comment]
Works for me. I'll merge it now then.

**Comment by kbrabrand** [comment]
Could you log on IRC, @fangel? I have an issue that I would like your input on if you have a few minutes..

**Pull request merged**
