### PR TITLE
Added use Exception so it handle errors

### PR DESCRIPTION
**Pull request by sgulseth**

### CODE REVIEW

**Comment by rexxars** [comment]
If you have the time, could you add a test for this as well? Just mock the client and have it throw an exception when `search()` is called?

**Comment by sgulseth** [comment]
Tests added

**Comment by sgulseth** [comment]
5.4 tests failed with 
```shell
 - The requested PHP extension ext-imagick >=3.0.1 is missing from your system. Install or enable PHP's imagick extension.
```

**Comment by kbrabrand** [comment]
Sorry for not responding here before now. Been busy with christmas++.

After merging #32 this PR was behind master and since I didn't want to bug you during christmas I've just pulled your branch and rebased with master, @sgulseth. Hope that's ok.

**Comment by sgulseth** [comment]
All right, thanks!

**Pull request closed without merging**
