### PR TITLE
Partial metadata search abstraction and ES backend implementation

### PR DESCRIPTION
**Pull request by kbrabrand**
More pieces to the metadata search puzzle. I've added a build file (rake) and a travis config as well as the start of a behat suite - currently with only parts of the first feature.

I guess with this, you'll be closer to testing that you implementation actually produces something that can be consumed by the ES PHP client, @fangel.

### CODE REVIEW

**Comment by fangel** [comment]
Looks like a great start to integration tests.

I think the Imbo PHP-CS requires single use-statements, e.g.


````
FILE: ...mbo-metadata-search/library/EventListener/MetadataOperations.php
----------------------------------------------------------------------
FOUND 3 ERRORS AND 1 WARNING AFFECTING 4 LINES
----------------------------------------------------------------------
  6 | ERROR   | Multiple use statements are not allowed
  7 | ERROR   | Multiple use statements are not allowed
  8 | ERROR   | Multiple use statements are not allowed
 68 | WARNING | The method parameter $event is never used
----------------------------------------------------------------------
````

I don't know if that's something to address sooner rather than later, or if we'll fix that up later?

**Comment by kbrabrand** [comment]
Behat is a learning process for me, and I just realized that the problem with JSON strings can be fixed by using regexps.

I'll redo my last few commits and fix the CS issues as well before merging.

**Comment by fangel** [comment]
I've never really properly used Behat either - so I'll be a good learning experience :+1:

**Comment by kbrabrand** [comment]
@fangel: I've fixed the use statements. There is still a few warnings left, but those are all related to methods that has to be implemented so I let them be.

**Comment by fangel** [comment]
Great! Let's merge this in and then see what parts are missing, and where we need more tests.

**Comment by kbrabrand** [comment]
:clap:

**Pull request merged**
