### PR TITLE
Docs, cleanup and annotations

### PR DESCRIPTION
**Pull request by kbrabrand**
Cleaning up in the feature contexts, added annotations, changed the route to conform with endpoint naming in Imbo.

### CODE REVIEW

**Comment by fangel** [comment]
Looks great. There once was a discussion on whether or not the end-point should be 

````
SEARCH /users/[publicKey]/images
````

Or if it should be

````
GET /users/[publicKey]/search
````

Currently, this plugin is using the latter - but I can't remember where the discussion ended on which one was preferable.

**Comment by kbrabrand** [comment]
Yes. I remember the discussion.. I read through the discussion when implementing and it was unclear to me. After some discussion here at the office I landed on using `GET` and introducing `../search`.

**Comment by fangel** [comment]
Sorry, I forgot about this. Merging now.

**Comment by kbrabrand** [comment]
No worries

**Pull request merged**
