### PR TITLE
Change the generated ElasticSearch queries to use the current syntax

### LINKED ISSUE #37: Documents inserted into ElasticSearch has a query-property
I'm currently looking into some improvements that we want to do on our metadata-search, so I was looking into the raw data that got stored in ElasticSearch, and I noticed something strange. All of the documents include the following 

```json
...,
"mime": "...",
"query": {
  "filtered": {
    "filter": {
      "and": []
    }
  }
},
"size": ...,
...
````

That seemed a little suspicious, and like a artefact of some search-query. So I looked around a bit, and have figured out it's because the same function, [prepareParams](https://github.com/imbo/imbo-metadata-search/blob/b2c77728f25088403024570808cb65280c45ec4e/library/Backend/ElasticSearch.php#L208) is called from both `set` and `search`, and by default it populates a default search-query for the `search` functionality so that the later functions can always just extend that filter.

```php
if (isset($params['body']['query']['filtered']['filter'][0])) {
  ...
} else {
  $params['body']['query']['filtered']['filter'] = ['and' => []];
}
````

But this is has the side-effect of also injecting the default search query into all the documents that are stored, which is probably not ideal.

I can take a look at fixing this, if you want - I would probably just move the query-part of `prepareParams` into `search`...

### LINKED ISSUE #38: Incompatible with ElasticSearch 5.2
The part of the ElasticSearch Search-DSL that we are using in the E.S.-backend was deprecated in 2.0.0-beta, and doesn't work in 5.2 (I haven't checked 5.1, and I think we run 5.0 in production where it works).

So we should update the ElasticSearch DSL-transformation to use a syntax that works from 2.0 and upwards.

We currently use the `filtered`-syntax, and we should probably move over to the `bool`-syntax - I've made a few tests that indicate that the `bool`-syntax seems to support the types of query that we support.

But what are peoples opinion on this? Should we simply change the transformation, which means that pre-2.0 will stop working (and thus should bump the semver-major version of this package), or should we have two different E.S.-backends depending on which version you run?

### PR DESCRIPTION
**Pull request by fangel**
The current elasticsearch query-syntax we use have been deprecated since 2.0, and the syntax that it now uses have been supported since at least then.

This PR fixes #37 and #38.

Note that this means that the minimum server-requirement wrt elasticsearch is 2.0. The public API for this plugin is unchanged, and any queries that was supported is still supported - it just uses a different, but equivalent, query to find the results in elasticsearch. What this means for the semver of this package, I'm not quite sure of.

Side-question: Should the PR be against develop or master - it doesn't look from the repo history like develop is used for anything.

### CODE REVIEW

**Comment by fangel** [comment]
It appears as if the version of ElasticSearch being run on the Travis-nodes doesn't support `filter`-queries within `bool`-queries. The only version that doesn't support that is 1.x - so it would appear as if we are being struck by the newly imposed minimum-version.

I'll try and figure out how to get Travis to use a later version of ElasticSearch.

**Comment by fangel** [comment]
Crikey, it's hard to debug what Travis is doing. Managed to bump Elasticsearch to version to 2.4.4 (I think). Now I just get failures when it tries to index documents.

I'll have to change the log what that happens to try and figure out what is wrong.

**Comment by christeredvartsen** [comment]
To follow how other imbo-related repositories should work, master should be the latest release in the current major. Once we release a new major, the current master should then be made into a separate branch so it can be updated with critical bug fixes separate from the new master. So I'd like to have a develop for development purposes.

**Comment by fangel** [comment]
Okay, I finally managed to find a way to upgrade the version of ES used by Travis to 2.4, and now the tests passes. So I'm pretty happy with how this works now.

I take it I should squash some of the commits a bit, so there is only one commit about Travis and Elasticsearch?

And just to make sure, I leave this PR against `master`, and then once we release a new (stable) version, any new ones should go towards `develop`?

**Comment by fangel** [comment]
Okay, I've cleaned up the commits regarding Travis, so it's a bit more tidy now. So if anyone wants to take a stab at reviewing them, that would be lovely.

**Comment by christeredvartsen** [comment]
> And just to make sure, I leave this PR against `master`, and then once we release a new (stable) version, any new ones should go towards `develop`?

Sounds like a plan.

> So if anyone wants to take a stab at reviewing them, that would be lovely.

I can have a look at this later today.

**Comment by christeredvartsen** [comment]
Looks fine. :+1: 

I'm guessing this warrants a major-bump as it kinda breaks BC by bumping an external dependency.

Have you tested this against the latest release of Elasticsearch (5.2) btw?

**Comment by christeredvartsen** [comment]
Can you verify that all examples in the README are still valid?

**Comment by christeredvartsen** [comment]
Not entirely sure what to do regards the version

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API.
>
> http://semver.org/#spec-item-8

And later on:

> What should I do if I update my own dependencies without changing the public API?
>
> That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality.
> 
> http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

According to this we might as well just release `2.2` and on with our lives.

**Comment by fangel** [comment]
> Have you tested this against the latest release of Elasticsearch (5.2) btw?

Yes, I actually only started this work because I wanted to work on improving the order of which results was returned, and setup a 5.2 instance using the latest docker-image of E.S., and then suddenly nothing worked.
Coincidently the issue with improving the order of returned hits will also be fixed by this issue.

The problem with the ordering is that we relied pretty exclusively on filters for our search (because they had easy `and` and `or`-clauses), and filters only include/exclude documents, but doesn't contribute to the score the documents receive for how much they apply. So by changing over to this new search-syntax, the `match`-clauses are now part of the query, and not the filter, which means that they help impact the score of the document, which means that better matching documents get a better score, and are thus returned before other documents with worse matchings.

> Can you verify that all examples in the README are still valid?

I think most of them are covered in some way or another in the unit or behat-tests. I'll double-check to make sure.

> According to this we might as well just release 2.2 and on with our lives.

Yeah, sounds like that might be the case.

**Comment by fangel** [comment]
I added quite a few more tests to the Behat-suite, and actually found a bug in what I've done. The `$or`-searches didn't work as expected.

If you had both a `should` and a `filter`-clause, it was very happy with none of the parts in the `should`-clause matching. This was fixed by adding `minimum_should_match` to 1, which makes it work the way you think it would.

**Comment by fangel** [comment]
@christeredvartsen I just added an extra behat-test to assess that the new type of queries actually do reasonable relevance-sorts as well.
I then had to remove the APCU-pecl extension from Travis as installing it started breaking the 5.6 build (but APCU extension was never used - so I think it was just leftovers from being copied from the main Imbo repo)

If you're okay with it, I'll merge this into develop today and then try and throw it on our staging servers to see how it behaves before then merging into master and doing a release.

**Comment by christeredvartsen** [comment]
Looks good! :+1:

**Pull request merged**
